# PlatformIO pre-build script: gzips the basic portal and the shared stylesheet from
# src/web_pages.cpp into a generated header, so Atlas sends ~1/4 of the bytes
# per page load. Wi-Fi transmit buffers come out of the same small heap as
# everything else. (The full portal ships as the SD pack.)
#
# src/web_pages.cpp stays the one source (host smoke tests read it too). The
# firmware serves the gzip copies when TURNHUB_GZIP_PAGES is defined; host
# builds do not run this script and keep the plain pages.
Import("env")  # noqa: F821 (provided by PlatformIO)

import gzip
import pathlib
import re

PAGES = (
    ("BASIC_PORTAL_HTML", "HTML"),
    ("THEME_CSS", "CSS"),
)

project = pathlib.Path(env.subst("$PROJECT_DIR"))  # noqa: F821
source = (project / "src" / "web_pages.cpp").read_text(encoding="utf-8")
# The compiler sees raw-string newlines as LF whatever the checkout uses.
source = source.replace("\r\n", "\n")

lines = [
    "// Generated by tools/gzip_web_pages.py from src/web_pages.cpp; do not edit.",
    "#pragma once",
    "#include <Arduino.h>",
    "namespace TurnHubWeb {",
]
for name, delimiter in PAGES:
    match = re.search(
        r"const char %s\[\] PROGMEM = R\"%s\((.*?)\)%s\";" % (name, delimiter, delimiter),
        source,
        re.S,
    )
    if match is None:
        raise SystemExit("gzip_web_pages.py: %s not found in src/web_pages.cpp" % name)
    data = gzip.compress(match.group(1).encode("utf-8"), compresslevel=9, mtime=0)
    lines.append("const uint8_t %s_GZIP[] PROGMEM = {" % name)
    for i in range(0, len(data), 24):
        lines.append("  " + ",".join(str(b) for b in data[i:i + 24]) + ",")
    lines.append("};")
    print("gzip_web_pages: %s %d -> %d bytes" % (name, len(match.group(1).encode("utf-8")), len(data)))
lines.append("}  // namespace TurnHubWeb")
text = "\n".join(lines) + "\n"

out_dir = pathlib.Path(env.subst("$PROJECT_BUILD_DIR")) / env.subst("$PIOENV") / "generated"  # noqa: F821
out_dir.mkdir(parents=True, exist_ok=True)
header = out_dir / "web_pages_gzip.h"
# Rewrite only on change, so unchanged pages don't force a rebuild.
if not header.exists() or header.read_text(encoding="utf-8") != text:
    header.write_text(text, encoding="utf-8")

env.Append(CPPPATH=[str(out_dir)], CPPDEFINES=["TURNHUB_GZIP_PAGES"])  # noqa: F821
