// Generated by design/build_tokens.py from design/tokens.json. Do not edit.
@file:Suppress("unused", "MagicNumber")

package com.turnhub.android.ui.theme

import androidx.annotation.DrawableRes
import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.em
import androidx.compose.ui.unit.sp
import com.turnhub.android.R

/** One theme's colors (design/tokens.json). Translucent values are already alpha-encoded. */
@Immutable
data class TokenColors(
    val bg: Color,
    val surface1: Color,
    val surface2: Color,
    val surface3: Color,
    val fill: Color,
    val fillStrong: Color,
    val separator: Color,
    val separatorStrong: Color,
    val text: Color,
    val textSecondary: Color,
    val textTertiary: Color,
    val accent: Color,
    val accentPressed: Color,
    val onAccent: Color,
    val accentSoft: Color,
    val turn: Color,
    val onTurn: Color,
    val turnSoft: Color,
    val good: Color,
    val warning: Color,
    val critical: Color,
    val info: Color,
    val focus: Color,
    val scrim: Color,
    val glowA: Color,
    val glowB: Color,
)

/** The themes in design/tokens.json, in order. */
enum class TokenTheme(
    val key: String,
    val label: String,
    val blurb: String,
    val dark: Boolean,
    val serifDisplay: Boolean,
    val brassOrnament: Boolean,
    val colors: TokenColors,
) {
    GRAPHITE(
        key = "graphite",
        label = "Graphite",
        blurb = "Modern dark. The default on dark devices.",
        dark = true,
        serifDisplay = false,
        brassOrnament = false,
        colors = TokenColors(bg = Color(0xFF0A0B0E), surface1 = Color(0xFF14161B), surface2 = Color(0xFF1B1E25), surface3 = Color(0xFF262A33), fill = Color(0x12FFFFFF), fillStrong = Color(0x24FFFFFF), separator = Color(0x1AFFFFFF), separatorStrong = Color(0x38FFFFFF), text = Color(0xFFF4F6FA), textSecondary = Color(0xFFA7AFBC), textTertiary = Color(0xFF828A99), accent = Color(0xFFF5B53F), accentPressed = Color(0xFFDDA02E), onAccent = Color(0xFF1B1303), accentSoft = Color(0x24F5B53F), turn = Color(0xFF3DDBB1), onTurn = Color(0xFF03231A), turnSoft = Color(0x293DDBB1), good = Color(0xFF45D98A), warning = Color(0xFFFFA24C), critical = Color(0xFFFF6B66), info = Color(0xFF72AEFF), focus = Color(0xFF8CBBFF), scrim = Color(0xA8000000), glowA = Color(0x00000000), glowB = Color(0x00000000)),
    ),
    DAYLIGHT(
        key = "daylight",
        label = "Daylight",
        blurb = "Modern light. The default on light devices.",
        dark = false,
        serifDisplay = false,
        brassOrnament = false,
        colors = TokenColors(bg = Color(0xFFF2F3F6), surface1 = Color(0xFFFFFFFF), surface2 = Color(0xFFF7F8FA), surface3 = Color(0xFFEBEDF1), fill = Color(0x0D0F172A), fillStrong = Color(0x1C0F172A), separator = Color(0x1A0F172A), separatorStrong = Color(0x380F172A), text = Color(0xFF0D1117), textSecondary = Color(0xFF4A5260), textTertiary = Color(0xFF646B78), accent = Color(0xFF9A5D00), accentPressed = Color(0xFF7E4C00), onAccent = Color(0xFFFFFFFF), accentSoft = Color(0x1FC27A0A), turn = Color(0xFF00775E), onTurn = Color(0xFFFFFFFF), turnSoft = Color(0x1F00876A), good = Color(0xFF18794A), warning = Color(0xFFA35200), critical = Color(0xFFC72B2B), info = Color(0xFF1F64C4), focus = Color(0xFF1F64C4), scrim = Color(0x660D1117), glowA = Color(0x00000000), glowB = Color(0x00000000)),
    ),
    BRASS(
        key = "brass",
        label = "Brass",
        blurb = "Warm gold and walnut, like the Atlas screen.",
        dark = true,
        serifDisplay = true,
        brassOrnament = true,
        colors = TokenColors(bg = Color(0xFF110D09), surface1 = Color(0xFF1B1510), surface2 = Color(0xFF241C14), surface3 = Color(0xFF30251A), fill = Color(0x14DEB064), fillStrong = Color(0x29DEB064), separator = Color(0x33DEB064), separatorStrong = Color(0x70DEB064), text = Color(0xFFF6ECD9), textSecondary = Color(0xFFC9B594), textTertiary = Color(0xFFA18F72), accent = Color(0xFFE2AE4A), accentPressed = Color(0xFFC9952F), onAccent = Color(0xFF1C1205), accentSoft = Color(0x24E2AE4A), turn = Color(0xFF62D6B2), onTurn = Color(0xFF06231B), turnSoft = Color(0x2962D6B2), good = Color(0xFF93DC8C), warning = Color(0xFFFFA25C), critical = Color(0xFFFF7D70), info = Color(0xFFA6C8EA), focus = Color(0xFFFFE28F), scrim = Color(0xA8000000), glowA = Color(0x2BE0A848), glowB = Color(0x0F5FD4B0)),
    ),
    CONTRAST(
        key = "contrast",
        label = "High contrast",
        blurb = "Maximum legibility. Chosen automatically when your device asks for more contrast.",
        dark = true,
        serifDisplay = false,
        brassOrnament = false,
        colors = TokenColors(bg = Color(0xFF000000), surface1 = Color(0xFF000000), surface2 = Color(0xFF0E0E0E), surface3 = Color(0xFF1C1C1C), fill = Color(0x1FFFFFFF), fillStrong = Color(0x3DFFFFFF), separator = Color(0xFFBDBDBD), separatorStrong = Color(0xFFFFFFFF), text = Color(0xFFFFFFFF), textSecondary = Color(0xFFECECEC), textTertiary = Color(0xFFD0D0D0), accent = Color(0xFFFFD400), accentPressed = Color(0xFFFFE45C), onAccent = Color(0xFF000000), accentSoft = Color(0x33FFD400), turn = Color(0xFF00F0D8), onTurn = Color(0xFF000000), turnSoft = Color(0x3300F0D8), good = Color(0xFF7DFF9B), warning = Color(0xFFFFB000), critical = Color(0xFFFF9A9A), info = Color(0xFF8FD3FF), focus = Color(0xFFFFFFFF), scrim = Color(0xCC000000), glowA = Color(0x00000000), glowB = Color(0x00000000)),
    ),
    ;

    companion object {
        val DEFAULT_DARK = GRAPHITE
        val DEFAULT_LIGHT = DAYLIGHT
        val MORE_CONTRAST = CONTRAST
        fun fromKey(key: String?): TokenTheme? = entries.firstOrNull { it.key == key }
    }
}

/** A type-scale step. [tabular] asks for tabular figures (clocks, life totals). */
@Immutable
data class TokenTextStyle(
    val size: TextUnit,
    val lineHeight: TextUnit,
    val weight: FontWeight,
    val tracking: TextUnit,
    val tabular: Boolean,
)

object DesignTokens {
    object Type {
        val caption = TokenTextStyle(12.sp, 16.sp, FontWeight(500), 0.01.em, false)
        val footnote = TokenTextStyle(13.sp, 18.sp, FontWeight(400), 0.0.em, false)
        val subhead = TokenTextStyle(15.sp, 20.sp, FontWeight(400), (-0.005).em, false)
        val body = TokenTextStyle(16.sp, 24.sp, FontWeight(400), (-0.01).em, false)
        val headline = TokenTextStyle(16.sp, 22.sp, FontWeight(600), (-0.01).em, false)
        val eyebrow = TokenTextStyle(12.sp, 16.sp, FontWeight(600), 0.08.em, false)
        val title3 = TokenTextStyle(20.sp, 26.sp, FontWeight(600), (-0.015).em, false)
        val title2 = TokenTextStyle(24.sp, 30.sp, FontWeight(650), (-0.02).em, false)
        val title1 = TokenTextStyle(30.sp, 36.sp, FontWeight(700), (-0.022).em, false)
        val largeTitle = TokenTextStyle(36.sp, 42.sp, FontWeight(750), (-0.025).em, false)
        val clock = TokenTextStyle(56.sp, 60.sp, FontWeight(650), (-0.03).em, true)
        val hero = TokenTextStyle(72.sp, 76.sp, FontWeight(700), (-0.035).em, true)
        val mega = TokenTextStyle(112.sp, 112.sp, FontWeight(750), (-0.04).em, true)
    }

    object Space {
        val s0: Dp = 0.dp
        val s1: Dp = 2.dp
        val s2: Dp = 4.dp
        val s3: Dp = 8.dp
        val s4: Dp = 12.dp
        val s5: Dp = 16.dp
        val s6: Dp = 20.dp
        val s7: Dp = 24.dp
        val s8: Dp = 32.dp
        val s9: Dp = 40.dp
        val s10: Dp = 48.dp
        val s11: Dp = 64.dp
    }

    object Radius {
        val xs: Dp = 6.dp
        val sm: Dp = 10.dp
        val md: Dp = 14.dp
        val lg: Dp = 20.dp
        val xl: Dp = 28.dp
        val full: Dp = 999.dp
    }

    object Elevation {
        val e1: Dp = 1.dp
        val e2: Dp = 6.dp
        val e3: Dp = 16.dp
    }

    object Motion {
        const val INSTANT_MS = 90
        const val FAST_MS = 160
        const val BASE_MS = 260
        const val SLOW_MS = 420
        const val SNAPPY_DAMPING = 0.82f
        const val SNAPPY_STIFFNESS = 700.0f
        const val GENTLE_DAMPING = 0.9f
        const val GENTLE_STIFFNESS = 240.0f
        const val BOUNCY_DAMPING = 0.62f
        const val BOUNCY_STIFFNESS = 420.0f
    }

    object Layout {
        val touchTarget: Dp = 44.dp
        val gutter: Dp = 16.dp
        val maxContent: Dp = 1200.dp
        val tabBar: Dp = 64.dp
    }

    /** The shared icon set (design/icons), as vector drawables. */
    object Icons {
        @DrawableRes val alert: Int = R.drawable.ic_th_alert
        @DrawableRes val battery: Int = R.drawable.ic_th_battery
        @DrawableRes val bell: Int = R.drawable.ic_th_bell
        @DrawableRes val book: Int = R.drawable.ic_th_book
        @DrawableRes val chart: Int = R.drawable.ic_th_chart
        @DrawableRes val check: Int = R.drawable.ic_th_check
        @DrawableRes val chevronDown: Int = R.drawable.ic_th_chevron_down
        @DrawableRes val chevronLeft: Int = R.drawable.ic_th_chevron_left
        @DrawableRes val chevronRight: Int = R.drawable.ic_th_chevron_right
        @DrawableRes val chevronUp: Int = R.drawable.ic_th_chevron_up
        @DrawableRes val clock: Int = R.drawable.ic_th_clock
        @DrawableRes val close: Int = R.drawable.ic_th_close
        @DrawableRes val contrast: Int = R.drawable.ic_th_contrast
        @DrawableRes val crown: Int = R.drawable.ic_th_crown
        @DrawableRes val dice: Int = R.drawable.ic_th_dice
        @DrawableRes val download: Int = R.drawable.ic_th_download
        @DrawableRes val edit: Int = R.drawable.ic_th_edit
        @DrawableRes val eye: Int = R.drawable.ic_th_eye
        @DrawableRes val flag: Int = R.drawable.ic_th_flag
        @DrawableRes val heart: Int = R.drawable.ic_th_heart
        @DrawableRes val home: Int = R.drawable.ic_th_home
        @DrawableRes val hub: Int = R.drawable.ic_th_hub
        @DrawableRes val info: Int = R.drawable.ic_th_info
        @DrawableRes val link: Int = R.drawable.ic_th_link
        @DrawableRes val lock: Int = R.drawable.ic_th_lock
        @DrawableRes val logout: Int = R.drawable.ic_th_logout
        @DrawableRes val minus: Int = R.drawable.ic_th_minus
        @DrawableRes val moon: Int = R.drawable.ic_th_moon
        @DrawableRes val more: Int = R.drawable.ic_th_more
        @DrawableRes val palette: Int = R.drawable.ic_th_palette
        @DrawableRes val pass: Int = R.drawable.ic_th_pass
        @DrawableRes val pause: Int = R.drawable.ic_th_pause
        @DrawableRes val play: Int = R.drawable.ic_th_play
        @DrawableRes val plus: Int = R.drawable.ic_th_plus
        @DrawableRes val power: Int = R.drawable.ic_th_power
        @DrawableRes val qr: Int = R.drawable.ic_th_qr
        @DrawableRes val refresh: Int = R.drawable.ic_th_refresh
        @DrawableRes val shield: Int = R.drawable.ic_th_shield
        @DrawableRes val sigil: Int = R.drawable.ic_th_sigil
        @DrawableRes val signal: Int = R.drawable.ic_th_signal
        @DrawableRes val skull: Int = R.drawable.ic_th_skull
        @DrawableRes val sliders: Int = R.drawable.ic_th_sliders
        @DrawableRes val sparkle: Int = R.drawable.ic_th_sparkle
        @DrawableRes val sun: Int = R.drawable.ic_th_sun
        @DrawableRes val swap: Int = R.drawable.ic_th_swap
        @DrawableRes val timer: Int = R.drawable.ic_th_timer
        @DrawableRes val trash: Int = R.drawable.ic_th_trash
        @DrawableRes val unlock: Int = R.drawable.ic_th_unlock
        @DrawableRes val upload: Int = R.drawable.ic_th_upload
        @DrawableRes val user: Int = R.drawable.ic_th_user
        @DrawableRes val users: Int = R.drawable.ic_th_users
        @DrawableRes val volume: Int = R.drawable.ic_th_volume
        @DrawableRes val wifi: Int = R.drawable.ic_th_wifi
    }

    /** The player avatars (design/avatars), by the preset key from GET /api/avatars. */
    object Avatars {
        @DrawableRes
        fun forKey(key: String): Int? = when (key) {
            "die" -> R.drawable.ic_avatar_die
            "crown" -> R.drawable.ic_avatar_crown
            "sword" -> R.drawable.ic_avatar_sword
            "shield" -> R.drawable.ic_avatar_shield
            "star" -> R.drawable.ic_avatar_star
            "moon" -> R.drawable.ic_avatar_moon
            "flame" -> R.drawable.ic_avatar_flame
            "tree" -> R.drawable.ic_avatar_tree
            "cat" -> R.drawable.ic_avatar_cat
            "skull" -> R.drawable.ic_avatar_skull
            "gem" -> R.drawable.ic_avatar_gem
            "bolt" -> R.drawable.ic_avatar_bolt
            else -> null
        }
    }
}
