#!/usr/bin/env python3
"""Generate device Inter fonts from the licensed design/fonts source.
Requires freetype-py. Run from any directory; no network downloads needed.
"""
from pathlib import Path
import make_fonts as fonts
import freetype

ROOT = Path(fonts.ROOT)

def inter_face(_directory, weight):
    face = freetype.Face(str(ROOT / 'design/fonts/Inter-Variable.ttf'))
    axes = face.get_variation_info().axes
    face.set_var_design_coords([600 if axis.name == 'Weight' else axis.default for axis in axes])
    return face

# Equal advances for 0..9 give clocks and life totals the app's tabular figures.
# Rasterization does not apply OpenType shaping, so center each digit in the
# widest digit cell explicitly rather than relying on the font's tnum feature.
original_render = fonts.render

def tabular_render(face, size, ch):
    width, height, left, top, advance, rows = original_render(face, size, ch)
    if ch.isascii() and ch.isdigit():
        cell = max(original_render(face, size, digit)[4] for digit in '0123456789')
        left += (cell-advance)//2
        advance = cell
    return width, height, left, top, advance, rows

fonts.render = tabular_render
fonts.load_face = inter_face
fonts.HEADER_NOTE = '''// GENERATED by tools/fonts/make_modern_fonts.py; do not edit.
// Inter, Copyright 2020 The Inter Project Authors (https://github.com/rsms/inter).
// SIL Open Font License 1.1: design/fonts/OFL-Inter.txt.'''
# Match existing layout bands; titles and digits keep their measured fallbacks.
fonts.ATLAS_FONTS = [(name, 'Inter-600', size, chars, use) for name, _, size, chars, use in fonts.ATLAS_FONTS]
fonts.SIGIL_FONTS = [(name, 'Inter-600', size, chars, use) for name, _, size, chars, use in fonts.SIGIL_FONTS]
if __name__ == '__main__':
    fonts.write_atlas('', 'modern_fonts.h', 'ModernFonts')
    fonts.write_sigil('', 'modern_fonts.h', 'ModernFonts')
