from pathlib import Path
import gzip
root=Path(__file__).resolve().parents[2]
js=(root/'third_party/qrcode-generator/qrcode.js').read_bytes()
data=gzip.compress(js,mtime=0)
(root/'include/portal_qr_asset.h').write_text('// Generated by tests/host/build_qr_asset.py; qrcode-generator 1.4.4 (MIT).\n#pragma once\n#include <Arduino.h>\nnamespace TurnHubWeb {\nconst uint8_t QR_SCRIPT_GZIP[] PROGMEM = {\n'+''.join('  '+','.join(str(v) for v in data[i:i+24])+',\n' for i in range(0,len(data),24))+'};\n}\n')
