"""TurnHub configuration and constants."""

import os

# Serial
SERIAL_PORT = os.getenv("TURNHUB_SERIAL_PORT", "/dev/ttyUSB0")
SERIAL_BAUD = 9600
SERIAL_TIMEOUT = 0.05
ARDUINO_BOOT_WAIT = 2.0
RECONNECT_DELAY = 2.0

# Physical prototype modules
MODULE_IDS = [1, 2]

# Top-level states
STATE_LOBBY = "LOBBY"
STATE_STARTING = "STARTING"
STATE_RUNNING = "RUNNING"
STATE_PAUSED = "PAUSED"
STATE_GAME_OVER = "GAME_OVER"

# Button timing mirrors the Arduino firmware
LONG_PRESS_SECONDS = 2.0
WIN_HOLD_SECONDS = 5.0

# Warning timer
WARNING_MIN_MS = 5_000
WARNING_MAX_MS = 300_000
WARNING_STEP_MS = 5_000
WARNING_CAUTION_FRACTION = 0.75
WARNING_BLINK_INTERVAL = 0.50

# Blue LED behavior
NEW_TURN_FLASH_SECONDS = 3.0
NEW_TURN_FLASH_INTERVAL = 0.20
BREATHE_MIN = 0
BREATHE_MAX = 255
BREATHE_PERIOD_SECONDS = 2.6

# Lobby
LOBBY_IDLE_LED_TIME = 0.50
LOBBY_FLASH_ON = 0.18
LOBBY_FLASH_OFF = 0.18
LOBBY_FLASH_GAP = 3.0

# Start countdown
START_COUNTDOWN_SECONDS = 3.0
START_COUNTDOWN_FLASH_TIME = 0.25
START_COUNTDOWN_TONES = [1000, 1300, 1700]

# Main loop
LOOP_SLEEP_SECONDS = 0.01
