[platformio]
default_envs = sigil

[env:sigil]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    zinggjm/GxEPD2

build_flags =
    -DCORE_DEBUG_LEVEL=1

[env:sigil-wokwi]
extends = env:sigil
build_flags =
    ${env:sigil.build_flags}
    -DTURNHUB_WOKWI
build_src_flags =
    -include wokwi_espnow_shim.h
