#!/usr/bin/env python3
"""Builds TurnHub's design tokens for every client from design/tokens.json.

  python3 design/build_tokens.py          write the generated files
  python3 design/build_tokens.py --check  fail if a generated file is stale
                                          or a theme misses a contrast minimum

Outputs (all generated; edit tokens.json or design/icons/*.svg instead):

  design/dist/tokens.css                  CSS custom properties, @font-face,
                                          one block per theme
  design/dist/icons.svg                   SVG sprite (<symbol id="i-name">)
  Android/.../ui/theme/DesignTokens.kt    the same tokens for Compose
  Android/.../res/drawable/ic_th_*.xml    the icons as vector drawables

Standard library only, so it runs with PlatformIO's Python as well.
"""

from __future__ import annotations

import argparse
import json
import math
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DESIGN = ROOT / "design"
TOKENS = DESIGN / "tokens.json"
ICONS = DESIGN / "icons"
CSS_OUT = DESIGN / "dist" / "tokens.css"
SPRITE_OUT = DESIGN / "dist" / "icons.svg"
ANDROID_MAIN = ROOT / "Android" / "app" / "src" / "main"
KOTLIN_OUT = ANDROID_MAIN / "java" / "com" / "turnhub" / "android" / "ui" / "theme" / "DesignTokens.kt"
DRAWABLE_DIR = ANDROID_MAIN / "res" / "drawable"
DRAWABLE_PREFIX = "ic_th_"

HEADER = "Generated by design/build_tokens.py from design/tokens.json. Do not edit."
ICON_STROKE = "1.75"


# --- Colors ---------------------------------------------------------------------

def parse_hex(value: str) -> tuple[float, float, float, float]:
    m = re.fullmatch(r"#([0-9A-Fa-f]{6})([0-9A-Fa-f]{2})?", value)
    if not m:
        raise SystemExit(f"tokens.json: bad color {value!r} (use #RRGGBB or #RRGGBBAA)")
    rgb = m.group(1)
    alpha = int(m.group(2), 16) / 255 if m.group(2) else 1.0
    return (int(rgb[0:2], 16) / 255, int(rgb[2:4], 16) / 255, int(rgb[4:6], 16) / 255, alpha)


def over(top, bottom):
    a = top[3]
    return tuple(top[i] * a + bottom[i] * (1 - a) for i in range(3)) + (1.0,)


def luminance(c) -> float:
    def lin(v):
        return v / 12.92 if v <= 0.04045 else ((v + 0.055) / 1.055) ** 2.4
    return 0.2126 * lin(c[0]) + 0.7152 * lin(c[1]) + 0.0722 * lin(c[2])


def contrast_ratio(fg, bg) -> float:
    a, b = luminance(fg), luminance(bg)
    hi, lo = max(a, b), min(a, b)
    return (hi + 0.05) / (lo + 0.05)


def check_contrast(tokens) -> list[str]:
    problems = []
    for key, theme in tokens["themes"].items():
        colors = theme["color"]
        base = parse_hex(colors["bg"])
        for fg_name, bg_name, minimum in tokens["contrast"]["checks"]:
            bg = over(parse_hex(colors[bg_name]), base)
            fg = over(parse_hex(colors[fg_name]), bg)
            ratio = contrast_ratio(fg, bg)
            if ratio + 1e-9 < minimum:
                problems.append(f"{key}: {fg_name} on {bg_name} is {ratio:.2f}:1, needs {minimum}:1")
    return problems


def kebab(name: str) -> str:
    return re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", name).lower()


# --- Springs --------------------------------------------------------------------

def spring_curve(damping: float, stiffness: float):
    """Samples a unit-mass spring from 0 to 1 until it settles. Returns (ms, points)."""
    omega = math.sqrt(stiffness)
    zeta = damping
    dt = 1 / 600
    x, v, t = 0.0, 0.0, 0.0
    samples = [(0.0, 0.0)]
    settled_for = 0.0
    while t < 3.0:
        a = -2 * zeta * omega * v - omega * omega * (x - 1)
        v += a * dt
        x += v * dt
        t += dt
        samples.append((t, x))
        settled_for = settled_for + dt if abs(x - 1) < 0.002 and abs(v) < 0.02 else 0.0
        if settled_for > 0.03:
            break
    total = samples[-1][0]
    step = max(1, len(samples) // 40)
    points = samples[::step]
    if points[-1] != samples[-1]:
        points.append(samples[-1])
    return round(total * 1000), [(p[0] / total, p[1]) for p in points]


def css_linear(points) -> str:
    parts = []
    for i, (t, x) in enumerate(points):
        value = 1 if i == len(points) - 1 else round(x, 4)
        if i in (0, len(points) - 1):
            parts.append(f"{value:g}")
        else:
            parts.append(f"{value:g} {t * 100:.1f}%")
    return "linear(" + ", ".join(parts) + ")"


# --- CSS ------------------------------------------------------------------------

def shadow_css(layers) -> str:
    out = []
    for y, blur, spread, alpha in layers:
        if alpha == 0:
            continue
        out.append(f"0 {y}px {blur}px {spread}px rgb(0 0 0 / {alpha:g})")
    return ", ".join(out) or "none"


def theme_block(tokens, key) -> list[str]:
    theme = tokens["themes"][key]
    lines = [f"color-scheme:{theme['scheme']};"]
    for name, value in theme["color"].items():
        lines.append(f"--c-{kebab(name)}:{value};")
    display = "var(--font-serif)" if theme["display"] == "serif" else "var(--font-text)"
    lines.append(f"--font-display:{display};")
    lines.append(f"--ornament:{theme['ornament']};")
    for level, layers in tokens["elevation"][theme["scheme"]].items():
        lines.append(f"--shadow-{level}:{shadow_css(layers)};")
    return lines


def build_css(tokens, font_url: str = "../fonts/") -> str:
    """The stylesheet. font_url is where the .woff2 files sit relative to it."""
    out = [f"/* {HEADER} */"]
    for role in ("text", "serif"):
        font = tokens["font"][role]
        out.append(
            "@font-face{font-family:\"%s\";src:url(\"%s%s.woff2\") format(\"woff2\");"
            "font-weight:100 900;font-style:normal;font-display:swap}" % (font["family"], font_url, font["file"])
        )
    shared = [
        f"--font-text:\"{tokens['font']['text']['family']}\",{tokens['font']['text']['fallback']};",
        f"--font-serif:\"{tokens['font']['serif']['family']}\",{tokens['font']['serif']['fallback']};",
        f"--font-mono:{tokens['font']['mono']['fallback']};",
    ]
    for name, style in tokens["type"].items():
        if name.startswith("$"):
            continue
        k = kebab(name)
        shared.append(f"--t-{k}-size:{style['size'] / 16:g}rem;")
        shared.append(f"--t-{k}-line:{style['line'] / style['size']:.4g};")
        shared.append(f"--t-{k}-weight:{style['weight']};")
        shared.append(f"--t-{k}-tracking:{style['tracking']:g}em;")
    for name, px in tokens["space"].items():
        shared.append(f"--s-{name}:{px}px;")
    for name, px in tokens["radius"].items():
        shared.append(f"--r-{name}:{px}px;")
    motion = tokens["motion"]
    for name, ms in motion["duration"].items():
        shared.append(f"--dur-{name}:{ms}ms;")
    for name, bez in motion["ease"].items():
        shared.append(f"--ease-{name}:cubic-bezier({', '.join(f'{v:g}' for v in bez)});")
    springs = {}
    for name, spec in motion["spring"].items():
        ms, points = spring_curve(spec["dampingRatio"], spec["stiffness"])
        springs[name] = (ms, css_linear(points))
        shared.append(f"--spring-{name}-dur:{ms}ms;")
        shared.append(f"--spring-{name}:var(--ease-standard);")
    for name, px in tokens["layout"].items():
        shared.append(f"--{kebab(name)}:{px}px;")
    out.append(":root{" + "".join(shared) + "}")
    # linear() springs where the browser has them; cubic-bezier otherwise.
    out.append("@supports (transition-timing-function:linear(0, 1)){:root{"
               + "".join(f"--spring-{n}:{curve};" for n, (_, curve) in springs.items()) + "}}")

    defaults = tokens["defaults"]
    out.append(":root,[data-theme=%s]{%s}" % (defaults["dark"], "".join(theme_block(tokens, defaults["dark"]))))
    out.append("@media (prefers-color-scheme:light){:root:not([data-theme]){%s}}"
               % "".join(theme_block(tokens, defaults["light"])))
    out.append("@media (prefers-contrast:more){:root:not([data-theme]){%s}}"
               % "".join(theme_block(tokens, defaults["moreContrast"])))
    for key in tokens["themes"]:
        if key == defaults["dark"]:
            continue
        out.append("[data-theme=%s]{%s}" % (key, "".join(theme_block(tokens, key))))
    return "\n".join(out) + "\n"


# --- Icons ----------------------------------------------------------------------

def load_icons() -> dict[str, str]:
    icons = {}
    for path in sorted(ICONS.glob("*.svg")):
        text = path.read_text(encoding="utf-8")
        paths = re.findall(r'<path d="([^"]+)"', text)
        if not paths or "<circle" in text or "<rect" in text or "<line" in text:
            raise SystemExit(f"{path}: icons must be <path d=...> elements only (Android converts them)")
        icons[path.stem] = " ".join(paths)
    return icons


def build_sprite(icons) -> str:
    out = [f"<!-- {HEADER} -->",
           '<svg xmlns="http://www.w3.org/2000/svg" style="display:none">']
    for name, d in icons.items():
        out.append(f'<symbol id="i-{name}" viewBox="0 0 24 24" fill="none" stroke="currentColor" '
                   f'stroke-width="{ICON_STROKE}" stroke-linecap="round" stroke-linejoin="round"><path d="{d}"/></symbol>')
    out.append("</svg>")
    return "\n".join(out) + "\n"


def build_drawable(d: str) -> str:
    return (f"<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<!-- {HEADER} -->\n"
            "<vector xmlns:android=\"http://schemas.android.com/apk/res/android\"\n"
            "    android:width=\"24dp\"\n    android:height=\"24dp\"\n"
            "    android:viewportWidth=\"24\"\n    android:viewportHeight=\"24\">\n"
            f"    <path\n        android:pathData=\"{d}\"\n"
            "        android:fillColor=\"#00000000\"\n        android:strokeColor=\"#FF000000\"\n"
            f"        android:strokeWidth=\"{ICON_STROKE}\"\n"
            "        android:strokeLineCap=\"round\"\n        android:strokeLineJoin=\"round\" />\n"
            "</vector>\n")


# --- Kotlin ---------------------------------------------------------------------

def kotlin_color(value: str) -> str:
    r, g, b, a = parse_hex(value)
    return "Color(0x%02X%02X%02X%02X)" % (round(a * 255), round(r * 255), round(g * 255), round(b * 255))


def kotlin_float(v: float) -> str:
    text = f"{v:g}"
    if "." not in text and "e" not in text:
        text += ".0"
    return f"({text})" if v < 0 else text


def kotlin_ident(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9]", "_", name)


def camel(name: str) -> str:
    head, *rest = re.split(r"[^A-Za-z0-9]+", name)
    return head + "".join(w.capitalize() for w in rest)


def build_kotlin(tokens, icons) -> str:
    color_names = list(next(iter(tokens["themes"].values()))["color"].keys())
    for key, theme in tokens["themes"].items():
        if list(theme["color"].keys()) != color_names:
            raise SystemExit(f"tokens.json: theme {key} must define the same colors in the same order")
    o = [f"// {HEADER}",
         '@file:Suppress("unused", "MagicNumber")',
         "",
         "package com.turnhub.android.ui.theme",
         "",
         "import androidx.annotation.DrawableRes",
         "import androidx.compose.runtime.Immutable",
         "import androidx.compose.ui.graphics.Color",
         "import androidx.compose.ui.text.font.FontWeight",
         "import androidx.compose.ui.unit.Dp",
         "import androidx.compose.ui.unit.TextUnit",
         "import androidx.compose.ui.unit.dp",
         "import androidx.compose.ui.unit.em",
         "import androidx.compose.ui.unit.sp",
         "import com.turnhub.android.R",
         "",
         "/** One theme's colors (design/tokens.json). Translucent values are already alpha-encoded. */",
         "@Immutable",
         "data class TokenColors("]
    o += [f"    val {n}: Color," for n in color_names]
    o += [")", "",
          "/** The themes in design/tokens.json, in order. */",
          "enum class TokenTheme(",
          "    val key: String,",
          "    val label: String,",
          "    val blurb: String,",
          "    val dark: Boolean,",
          "    val serifDisplay: Boolean,",
          "    val brassOrnament: Boolean,",
          "    val colors: TokenColors,",
          ") {"]
    for key, theme in tokens["themes"].items():
        args = ", ".join(f"{n} = {kotlin_color(theme['color'][n])}" for n in color_names)
        o.append(f"    {key.upper()}(")
        o.append(f"        key = \"{key}\",")
        o.append(f"        label = \"{theme['label']}\",")
        o.append(f"        blurb = \"{theme['blurb']}\",")
        o.append(f"        dark = {'true' if theme['scheme'] == 'dark' else 'false'},")
        o.append(f"        serifDisplay = {'true' if theme['display'] == 'serif' else 'false'},")
        o.append(f"        brassOrnament = {'true' if theme['ornament'] == 'brass' else 'false'},")
        o.append(f"        colors = TokenColors({args}),")
        o.append("    ),")
    defaults = tokens["defaults"]
    o += ["    ;", "",
          "    companion object {",
          f"        val DEFAULT_DARK = {defaults['dark'].upper()}",
          f"        val DEFAULT_LIGHT = {defaults['light'].upper()}",
          f"        val MORE_CONTRAST = {defaults['moreContrast'].upper()}",
          "        fun fromKey(key: String?): TokenTheme? = entries.firstOrNull { it.key == key }",
          "    }",
          "}", "",
          "/** A type-scale step. [tabular] asks for tabular figures (clocks, life totals). */",
          "@Immutable",
          "data class TokenTextStyle(",
          "    val size: TextUnit,",
          "    val lineHeight: TextUnit,",
          "    val weight: FontWeight,",
          "    val tracking: TextUnit,",
          "    val tabular: Boolean,",
          ")", "",
          "object DesignTokens {",
          "    object Type {"]
    for name, s in tokens["type"].items():
        if name.startswith("$"):
            continue
        o.append(f"        val {name} = TokenTextStyle({s['size']}.sp, {s['line']}.sp, FontWeight({s['weight']}), "
                 f"{kotlin_float(s['tracking'])}.em, {'true' if s.get('tabular') else 'false'})")
    o += ["    }", "", "    object Space {"]
    for name, px in tokens["space"].items():
        o.append(f"        val s{name}: Dp = {px}.dp")
    o += ["    }", "", "    object Radius {"]
    for name, px in tokens["radius"].items():
        o.append(f"        val {name}: Dp = {px}.dp")
    o += ["    }", "", "    object Elevation {"]
    for name, dp in tokens["elevation"]["android"].items():
        o.append(f"        val e{name}: Dp = {dp}.dp")
    o += ["    }", "", "    object Motion {"]
    for name, ms in tokens["motion"]["duration"].items():
        o.append(f"        const val {name.upper()}_MS = {ms}")
    for name, spec in tokens["motion"]["spring"].items():
        o.append(f"        const val {name.upper()}_DAMPING = {kotlin_float(spec['dampingRatio'])}f")
        o.append(f"        const val {name.upper()}_STIFFNESS = {kotlin_float(spec['stiffness'])}f")
    o += ["    }", "", "    object Layout {"]
    for name, px in tokens["layout"].items():
        o.append(f"        val {name}: Dp = {px}.dp")
    o += ["    }", "", "    /** The shared icon set (design/icons), as vector drawables. */", "    object Icons {"]
    for name in icons:
        o.append(f"        @DrawableRes val {camel(name)}: Int = R.drawable.{DRAWABLE_PREFIX}{kotlin_ident(name)}")
    o += ["    }", "}", ""]
    return "\n".join(o)


# --- Main -----------------------------------------------------------------------

def outputs(tokens) -> dict[Path, str]:
    icons = load_icons()
    files = {
        CSS_OUT: build_css(tokens),
        SPRITE_OUT: build_sprite(icons),
        KOTLIN_OUT: build_kotlin(tokens, icons),
    }
    for name, d in icons.items():
        files[DRAWABLE_DIR / f"{DRAWABLE_PREFIX}{kotlin_ident(name)}.xml"] = build_drawable(d)
    return files


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args(argv)
    tokens = json.loads(TOKENS.read_text(encoding="utf-8"))

    problems = check_contrast(tokens)
    files = outputs(tokens)
    expected_drawables = {p for p in files if p.parent == DRAWABLE_DIR}
    stale_drawables = {p for p in DRAWABLE_DIR.glob(f"{DRAWABLE_PREFIX}*.xml")} - expected_drawables

    if args.check:
        for path, text in files.items():
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                problems.append(f"{path.relative_to(ROOT)} is stale; run python3 design/build_tokens.py")
        for path in sorted(stale_drawables):
            problems.append(f"{path.relative_to(ROOT)} has no icon in design/icons; run python3 design/build_tokens.py")
        if problems:
            print("\n".join(problems), file=sys.stderr)
            return 1
        print(f"Design tokens OK: {len(tokens['themes'])} themes, {len(files) - 3} icons.")
        return 0

    if problems:
        print("\n".join(problems), file=sys.stderr)
        return 1
    for path, text in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            path.write_text(text, encoding="utf-8", newline="\n")
    for path in stale_drawables:
        path.unlink()
    print(f"Wrote {len(files)} files ({len(tokens['themes'])} themes, {len(files) - 3} icons).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
