#!/usr/bin/env python3
"""Atlas alpha masks from vector masters; current Sigil assets remain frozen.

Regenerate with tools/artwork-requirements.txt. --check uses only stdlib to
verify source provenance and the generated artifact digest.
"""
import argparse
import hashlib
import io
import re
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'Atlas/include/avatar_masks.h'
SOURCES = sorted((ROOT / 'design/avatars').glob('*.svg'))

def digest():
    return hashlib.sha256(b''.join(p.name.encode() + b'\0' + p.read_bytes() for p in SOURCES)).hexdigest()

def main():
    parser = argparse.ArgumentParser(); parser.add_argument('--check', action='store_true'); args = parser.parse_args()
    if args.check:
        text = OUT.read_text()
        expected = re.search(r'// artifact-sha256: (\w+)\n', text)
        payload = text[:expected.start()] if expected else ''
        if f'// source-sha256: {digest()}\n' not in text or not expected or hashlib.sha256(payload.encode()).hexdigest() != expected[1]:
            raise SystemExit('Avatar masks stale or modified: run design/build_avatar_masks.py')
        print('Atlas avatar masks current: 12 vector masters, 64-pixel alpha masks'); return
    import cairosvg
    from PIL import Image
    text = '#pragma once\n// Generated by design/build_avatar_masks.py; do not edit.\n'
    text += f'// source-sha256: {digest()}\n#include <stdint.h>\n#include "avatars.h"\nnamespace TurnHubArtwork {{\nconstexpr uint8_t PRESET_SIDE = 64;\n'
    for p in SOURCES:
        raw = cairosvg.svg2png(bytestring=p.read_bytes(), output_width=256, output_height=256)
        alpha = Image.open(io.BytesIO(raw)).getchannel('A').resize((64,64), Image.Resampling.LANCZOS)
        values = list(alpha.getdata())
        text += f'constexpr uint8_t MASK_{p.stem}[4096] = {{\n'
        text += '\n'.join('  ' + ','.join(str(v) for v in values[i:i+64]) + ',' for i in range(0,4096,64)) + '\n};\n'
    text += '''inline const uint8_t *presetMask(uint8_t avatar) {
  const auto *icon = TurnHubAvatars::presetAvatar(avatar);
  if (!icon) return nullptr;
'''
    for p in SOURCES:
        text += f'  if (strcmp(icon->key, "{p.stem}") == 0) return MASK_{p.stem};\n'
    text += '  return nullptr;\n}\n} // namespace TurnHubArtwork\n'
    text += f'// artifact-sha256: {hashlib.sha256(text.encode()).hexdigest()}\n'
    OUT.write_text(text)
if __name__ == '__main__': main()
