// GENERATED by design/build_tokens.py; edit design/tokens.json.
#pragma once
#include <stdint.h>
namespace TurnHubTheme {
enum class Id : uint8_t { Graphite, Daylight, Brass, Contrast, Count };
inline bool valid(uint8_t id) { return id < static_cast<uint8_t>(Id::Count); }
inline Id next(Id id) { return static_cast<Id>((static_cast<uint8_t>(id) + 1) % static_cast<uint8_t>(Id::Count)); }
struct Palette { const char *key; const char *label; bool ornament; bool light; uint32_t bg; uint32_t surface1; uint32_t surface2; uint32_t surface3; uint32_t fill; uint32_t fillStrong; uint32_t separator; uint32_t separatorStrong; uint32_t text; uint32_t textSecondary; uint32_t textTertiary; uint32_t accent; uint32_t accentPressed; uint32_t onAccent; uint32_t accentSoft; uint32_t turn; uint32_t onTurn; uint32_t turnSoft; uint32_t good; uint32_t warning; uint32_t critical; uint32_t info; uint32_t focus; uint32_t scrim; uint32_t glowA; uint32_t glowB; };
inline const Palette &palette(Id id) {
  static const Palette values[] = {
    {"graphite", "Graphite", false, false, 0x0A0B0E, 0x14161B, 0x1B1E25, 0x262A33, 0x1B1C1F, 0x2D2D30, 0x232427, 0x404143, 0xF4F6FA, 0xA7AFBC, 0x828A99, 0xF5B53F, 0xDDA02E, 0x1B1303, 0x2B2315, 0x3DDBB1, 0x03231A, 0x122C28, 0x45D98A, 0xFFA24C, 0xFF6B66, 0x72AEFF, 0x8CBBFF, 0x030405, 0x0A0B0E, 0x0A0B0E},
    {"daylight", "Daylight", false, true, 0xF2F3F6, 0xFFFFFF, 0xF7F8FA, 0xEBEDF1, 0xE6E8EC, 0xD9DBE0, 0xDBDDE1, 0xC0C3C9, 0x0D1117, 0x4A5260, 0x646B78, 0x9A5D00, 0x7E4C00, 0xFFFFFF, 0xECE4D9, 0x00775E, 0xFFFFFF, 0xD5E6E5, 0x18794A, 0xA35200, 0xC72B2B, 0x1F64C4, 0x1F64C4, 0x96999D, 0xF2F3F6, 0xF2F3F6},
    {"brass", "Brass", true, false, 0x110D09, 0x1B1510, 0x241C14, 0x30251A, 0x211A10, 0x322718, 0x3A2E1B, 0x6B5531, 0xF6ECD9, 0xC9B594, 0xA18F72, 0xE2AE4A, 0xC9952F, 0x1C1205, 0x2F2412, 0x62D6B2, 0x06231B, 0x1E2D24, 0x93DC8C, 0xFFA25C, 0xFF7D70, 0xA6C8EA, 0xFFE28F, 0x060403, 0x342714, 0x161913},
    {"contrast", "High contrast", false, false, 0x000000, 0x000000, 0x0E0E0E, 0x1C1C1C, 0x1F1F1F, 0x3D3D3D, 0xBDBDBD, 0xFFFFFF, 0xFFFFFF, 0xECECEC, 0xD0D0D0, 0xFFD400, 0xFFE45C, 0x000000, 0x332A00, 0x00F0D8, 0x000000, 0x00302B, 0x7DFF9B, 0xFFB000, 0xFF9A9A, 0x8FD3FF, 0xFFFFFF, 0x000000, 0x000000, 0x000000},
  };
  return values[valid(static_cast<uint8_t>(id)) ? static_cast<uint8_t>(id) : 0];
}
} // namespace TurnHubTheme
